// <auto-generated />
using System;
using Academix.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academix.Infrastructure.Migrations
{
    [DbContext(typeof(AcademixDbContext))]
    [Migration("20240423144835_UpdatedSubjectsStudentsTable")]
    partial class UpdatedSubjectsStudentsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ExcusedAbsence")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Absences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2024, 4, 23, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(5048),
                            ExcusedAbsence = false,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2024, 4, 24, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(5082),
                            ExcusedAbsence = false,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2024, 4, 25, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(5084),
                            ExcusedAbsence = true,
                            StudentId = 1,
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a3717562-385e-41ce-9eff-0f1b994e5548",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e779399-25f3-4fe0-b29c-2a071e3b8042",
                            Email = "i.ivanov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "I.IVANOV@MAIL.COM",
                            NormalizedUserName = "I.IVANOV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENEz3UOFGHF6Cg24Pk5z9bN2vIJUdb0x40WLB757/SO3wA92IxTBCwowaeRmyqOKLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4cfce1e8-aa78-4b5e-be10-5c63a261dfdd",
                            TwoFactorEnabled = false,
                            UserName = "i.ivanov@mail.com"
                        },
                        new
                        {
                            Id = "1ae342a8-9fab-4c0a-bd5a-70b351717ecc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e736984f-ff91-4c15-b211-f5d1005e3850",
                            Email = "m.marinov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Mitko",
                            LastName = "Marinov",
                            LockoutEnabled = false,
                            NormalizedEmail = "M.MARINOV@MAIL.COM",
                            NormalizedUserName = "M.MARINOV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGXddOMQSF4JnIexid9/56BDgs/MC18OgkuXB8iH23kXZvyxSsodRLBWxkki2ysCqA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e442737a-c4d4-48c2-8da9-64431fdc9eec",
                            TwoFactorEnabled = false,
                            UserName = "m.marinov@mail.com"
                        },
                        new
                        {
                            Id = "a171483f-6e48-446a-a5d7-36110d0c1443",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "103f22e5-03fc-4639-8406-f4338d561598",
                            Email = "d.kirilov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Drago",
                            LastName = "Kirilov",
                            LockoutEnabled = false,
                            NormalizedEmail = "D.KIRILOV@MAIL.COM",
                            NormalizedUserName = "D.KIRILOV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB+FzBH+gL/1gz6q0h1oGNXJ79p/k3DjtXDLFV6t+JiHoW7JXfAw909nJD+pvA7T7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f3ed2ae-e8c5-4407-aa23-32e12301f2ae",
                            TwoFactorEnabled = false,
                            UserName = "d.kirilov@mail.com"
                        },
                        new
                        {
                            Id = "b2502a25-8341-4e5c-af74-cd0f889ede1b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0f5add5-0a49-4a93-8569-687be186bb5b",
                            Email = "m.kirilova@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Marta",
                            LastName = "Kirilova",
                            LockoutEnabled = false,
                            NormalizedEmail = "M.KIRILOVA@MAIL.COM",
                            NormalizedUserName = "M.KIRILOVA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELwp0aQGIevdK6m/MMzmM6D2eozangLpBZtf2FJS74bB1iUwS70SIDwq1uIvKuvNkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d8f49445-0a9a-400d-b316-dfddc60a5d79",
                            TwoFactorEnabled = false,
                            UserName = "m.kirilova@mail.com"
                        },
                        new
                        {
                            Id = "925da918-5cd0-4b17-9b62-2f417aac0343",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43761117-4ee3-4e47-bd38-2baed3ac9e0c",
                            Email = "v.marinov@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Vasil",
                            LastName = "Marinov",
                            LockoutEnabled = false,
                            NormalizedEmail = "V.MARINOV@MAIL.COM",
                            NormalizedUserName = "V.MARINOV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKFJafxgFmMEfLUV31qe1V01JfTVb6Y+p5EpIgUBhVnq0re+5T22G/W+PTXAWeuEUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20ac1349-5b2e-46bc-9c96-634db17b3cd6",
                            TwoFactorEnabled = false,
                            UserName = "v.marinov@mail.com"
                        },
                        new
                        {
                            Id = "24a0fdf5-ca4f-4c0f-8120-f6c87448033c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6240e20d-11ed-4d14-b29d-545489abb4a2",
                            Email = "v.kirilova@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Vanya",
                            LastName = "Kirilova",
                            LockoutEnabled = false,
                            NormalizedEmail = "V.KIRILOVA@MAIL.COM",
                            NormalizedUserName = "V.KIRILOVA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECfAluKkLissnc1+qhtLl0LXeHMhEpPTGVsMO1RL0PU4v1TG+Lcf3nauS66W1M4S8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb296357-2165-4445-ac44-5be6a032ccbd",
                            TwoFactorEnabled = false,
                            UserName = "v.kirilova@mail.com"
                        },
                        new
                        {
                            Id = "5093413e-4acb-471a-9ce7-53df30689fc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4679682-c567-4c7b-ba10-1c1836c129c7",
                            Email = "n.zakova@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Nikoleta",
                            LastName = "Zakova",
                            LockoutEnabled = false,
                            NormalizedEmail = "N.ZAKOVA@MAIL.COM",
                            NormalizedUserName = "N.ZAKOVA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOX2qm/lmSwdhJo7FTF3CyBm4Nnh4Xac97iI2r1A6Vy0JG/wshuiiJBhI1crC89Vpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1015ee81-ec2f-46ae-a5db-32f4f5a8aee1",
                            TwoFactorEnabled = false,
                            UserName = "n.zakova@mail.com"
                        },
                        new
                        {
                            Id = "6c1ff15b-1853-4d20-98ff-9695affb432c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf4ef2a7-8100-46a7-9dd6-1da033fbb9d9",
                            Email = "d.milev@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Dragan",
                            LastName = "Milev",
                            LockoutEnabled = false,
                            NormalizedEmail = "D.MILEV@MAIL.COM",
                            NormalizedUserName = "D.MILEV@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBgo+dhhCLta/riVB8Dzu7Ud4J0UDzhZz51m9nwhAqOW5m5YpdlRsg8b1SZbX+EEtg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff3c57af-3f20-4bc8-856a-1cfe08122344",
                            TwoFactorEnabled = false,
                            UserName = "d.milev@mail.com"
                        },
                        new
                        {
                            Id = "bd3e68c0-728b-44a0-ba3a-992d8ae683f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cab1660-d7d0-4d0e-a5a2-5fdf881ae832",
                            Email = "z.draganova@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Zara",
                            LastName = "Draganova",
                            LockoutEnabled = false,
                            NormalizedEmail = "Z.DRAGANOVA@MAIL.COM",
                            NormalizedUserName = "Z.DRAGANOVA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEK48hrNExl+s1cnnPWivYN0PX4B1V7xy5QZgRmv6T2C0//fG87o5P1pM5DjaVkOCpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b789528c-581a-4e30-b5cd-1568a6e44318",
                            TwoFactorEnabled = false,
                            UserName = "z.draganova@mail.com"
                        },
                        new
                        {
                            Id = "11f2b8bd-a49a-42cd-b08b-ce067e430965",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2baaf67-a31f-43c4-973f-c7453b2cd39b",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELGSpKEmHZOokupCmBHaKAe6dVXtS5fRFc2nWz54dp8Uw01RStBhZK2Oe6yfhHU4Tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e30a607b-a214-48a2-a9f4-d71efa1ca46b",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        },
                        new
                        {
                            Id = "214ce248-b8b3-4832-8c3b-7f133e7a429e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e8929fd-4506-415f-9eff-1b90048e14f8",
                            Email = "admin2@mail.com",
                            EmailConfirmed = false,
                            FirstName = "admin2",
                            LastName = "Admin2",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@MAIL.COM",
                            NormalizedUserName = "ADMIN2@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECc6wT+kNbJhrYv04o0r30dngewLg6h8Yz0ndJQPsBcc6b8DNnDaSR/QJ21O2PjPvg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f2add41-4602-469e-82e5-e54c09330f17",
                            TwoFactorEnabled = false,
                            UserName = "admin2@mail.com"
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Burgas"
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClassTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassTeacherId = 1,
                            Name = "12A",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassTeacherId = 2,
                            Name = "8B",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeNumber")
                        .HasColumnType("int");

                    b.Property<int>("GradeType")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2024, 4, 23, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(6108),
                            GradeNumber = 4,
                            GradeType = 0,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2024, 5, 5, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(6116),
                            GradeNumber = 6,
                            GradeType = 0,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2024, 5, 4, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(6119),
                            GradeNumber = 6,
                            GradeType = 1,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2024, 4, 30, 17, 48, 34, 832, DateTimeKind.Local).AddTicks(6121),
                            GradeNumber = 2,
                            GradeType = 0,
                            StudentId = 1,
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.RequestReceiver", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "ReceiverId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("RequestsReceivers");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.StudentParent", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("StudentsParents");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ParentId = "925da918-5cd0-4b17-9b62-2f417aac0343"
                        },
                        new
                        {
                            StudentId = 2,
                            ParentId = "24a0fdf5-ca4f-4c0f-8120-f6c87448033c"
                        },
                        new
                        {
                            StudentId = 3,
                            ParentId = "24a0fdf5-ca4f-4c0f-8120-f6c87448033c"
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.SubjectStudent", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SubjectsStudents");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            SubjectId = 3,
                            StudentId = 1
                        },
                        new
                        {
                            SubjectId = 1,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DirectorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DirectorId = "a3717562-385e-41ce-9eff-0f1b994e5548",
                            Name = "Vasil Levski"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "137 Georgi Asparuhov"
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("StudentIdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentIdentityId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vasil Aprilov 5",
                            ClassId = 1,
                            StudentIdentityId = "1ae342a8-9fab-4c0a-bd5a-70b351717ecc"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Krali Marko 12",
                            ClassId = 1,
                            StudentIdentityId = "a171483f-6e48-446a-a5d7-36110d0c1443"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kalimanci 13",
                            ClassId = 2,
                            StudentIdentityId = "b2502a25-8341-4e5c-af74-cd0f889ede1b"
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            SchoolId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            SchoolId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "History",
                            SchoolId = 1,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherIdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherIdentityId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SchoolId = 1,
                            TeacherIdentityId = "5093413e-4acb-471a-9ce7-53df30689fc1"
                        },
                        new
                        {
                            Id = 2,
                            SchoolId = 1,
                            TeacherIdentityId = "6c1ff15b-1853-4d20-98ff-9695affb432c"
                        },
                        new
                        {
                            Id = 3,
                            SchoolId = 1,
                            TeacherIdentityId = "bd3e68c0-728b-44a0-ba3a-992d8ae683f9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a550b411-e5c7-407f-aaba-35161bab127e",
                            ConcurrencyStamp = "c5b84a70-c5e6-4329-8053-6405c713a7a5",
                            Name = "Director",
                            NormalizedName = "DIRECTOR"
                        },
                        new
                        {
                            Id = "f67cd347-818b-4c3e-a1ce-ae76e1a2e31b",
                            ConcurrencyStamp = "631e2e09-a604-4aec-bc3e-7c8b9f124b10",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "e67d14b1-de35-47bd-96ac-a70fcc4c25be",
                            ConcurrencyStamp = "2da4a943-8bf0-46e0-8bb7-99f608879bae",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "fc1ee3a5-9b29-43ea-b038-2265c1806a75",
                            ConcurrencyStamp = "ed788692-87ab-45a1-84fc-38db75f9ae2f",
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        },
                        new
                        {
                            Id = "7f92327f-b1c1-4fd0-b837-afc278f256b2",
                            ConcurrencyStamp = "7cf51094-5a62-4c4d-b6c7-3044ce460b74",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "FullName",
                            ClaimValue = "Ivan Ivanov",
                            UserId = "a3717562-385e-41ce-9eff-0f1b994e5548"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "FullName",
                            ClaimValue = "Mitko Marinov",
                            UserId = "1ae342a8-9fab-4c0a-bd5a-70b351717ecc"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "FullName",
                            ClaimValue = "Drago Kirilov",
                            UserId = "a171483f-6e48-446a-a5d7-36110d0c1443"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "FullName",
                            ClaimValue = "Marta Kirilova",
                            UserId = "b2502a25-8341-4e5c-af74-cd0f889ede1b"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "FullName",
                            ClaimValue = "Vasil Marinov",
                            UserId = "925da918-5cd0-4b17-9b62-2f417aac0343"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "FullName",
                            ClaimValue = "Vanya Kirilova",
                            UserId = "24a0fdf5-ca4f-4c0f-8120-f6c87448033c"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "FullName",
                            ClaimValue = "Nikoleta Zakova",
                            UserId = "5093413e-4acb-471a-9ce7-53df30689fc1"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "FullName",
                            ClaimValue = "Dragan Milev",
                            UserId = "6c1ff15b-1853-4d20-98ff-9695affb432c"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "FullName",
                            ClaimValue = "Zara Draganova",
                            UserId = "bd3e68c0-728b-44a0-ba3a-992d8ae683f9"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "FullName",
                            ClaimValue = "admin Admin",
                            UserId = "11f2b8bd-a49a-42cd-b08b-ce067e430965"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "FullName",
                            ClaimValue = "admin2 Admin2",
                            UserId = "214ce248-b8b3-4832-8c3b-7f133e7a429e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a3717562-385e-41ce-9eff-0f1b994e5548",
                            RoleId = "a550b411-e5c7-407f-aaba-35161bab127e"
                        },
                        new
                        {
                            UserId = "5093413e-4acb-471a-9ce7-53df30689fc1",
                            RoleId = "f67cd347-818b-4c3e-a1ce-ae76e1a2e31b"
                        },
                        new
                        {
                            UserId = "6c1ff15b-1853-4d20-98ff-9695affb432c",
                            RoleId = "f67cd347-818b-4c3e-a1ce-ae76e1a2e31b"
                        },
                        new
                        {
                            UserId = "bd3e68c0-728b-44a0-ba3a-992d8ae683f9",
                            RoleId = "f67cd347-818b-4c3e-a1ce-ae76e1a2e31b"
                        },
                        new
                        {
                            UserId = "1ae342a8-9fab-4c0a-bd5a-70b351717ecc",
                            RoleId = "e67d14b1-de35-47bd-96ac-a70fcc4c25be"
                        },
                        new
                        {
                            UserId = "a171483f-6e48-446a-a5d7-36110d0c1443",
                            RoleId = "e67d14b1-de35-47bd-96ac-a70fcc4c25be"
                        },
                        new
                        {
                            UserId = "b2502a25-8341-4e5c-af74-cd0f889ede1b",
                            RoleId = "e67d14b1-de35-47bd-96ac-a70fcc4c25be"
                        },
                        new
                        {
                            UserId = "925da918-5cd0-4b17-9b62-2f417aac0343",
                            RoleId = "fc1ee3a5-9b29-43ea-b038-2265c1806a75"
                        },
                        new
                        {
                            UserId = "24a0fdf5-ca4f-4c0f-8120-f6c87448033c",
                            RoleId = "fc1ee3a5-9b29-43ea-b038-2265c1806a75"
                        },
                        new
                        {
                            UserId = "11f2b8bd-a49a-42cd-b08b-ce067e430965",
                            RoleId = "7f92327f-b1c1-4fd0-b837-afc278f256b2"
                        },
                        new
                        {
                            UserId = "214ce248-b8b3-4832-8c3b-7f133e7a429e",
                            RoleId = "7f92327f-b1c1-4fd0-b837-afc278f256b2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Absence", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Subject", "Subject")
                        .WithMany("Absences")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Class", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Teacher", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId");

                    b.HasOne("Academix.Infrastructure.Data.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Grade", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.RequestReceiver", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Request", "Request")
                        .WithMany("RequestReceivers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.StudentParent", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Student", "Student")
                        .WithMany("StudentParents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Mapping.SubjectStudent", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Student", "Student")
                        .WithMany("SubjectsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Subject", "Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Request", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Class");

                    b.Navigation("Requester");

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.School", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId");

                    b.Navigation("City");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Student", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "StudentIdentity")
                        .WithMany()
                        .HasForeignKey("StudentIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("StudentIdentity");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Subject", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.School", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Teacher", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", "TeacherIdentity")
                        .WithMany()
                        .HasForeignKey("TeacherIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("TeacherIdentity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Academix.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Request", b =>
                {
                    b.Navigation("RequestReceivers");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Grades");

                    b.Navigation("StudentParents");

                    b.Navigation("SubjectsStudent");
                });

            modelBuilder.Entity("Academix.Infrastructure.Data.Models.Subject", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Grades");

                    b.Navigation("SubjectStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
